language: node_js
node_js:
    - "node"
    - "iojs"
    - "4.0"

addons:
    code_climate:
        repo_token: 1ad66bb2f846ef22195ece5719e1d77dc05916afa2c4b83ad4da66ef4622999c

after_script:
    - node node_modules/istanbul/lib/cli.js cover js/app.js
    - codeclimate-test-reporter < coverage/lcov.info
    - ls -lsa .
